### ISSUE TITLE
VFS: Cannot open root device

### ISSUE THREAD

**Issue by Haragius** [Lamobo/Lamobo-D1#3]
There is something wrong in the current kernel.

VFS: Cannot open root device "mtdblock1" or unknown-block(0,0): error -6
Please append a correct "root=" boot option; here are the available partitions:
1f00 16384 mtdblock0 (driver?)
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)

At the moment i cant figured out where the problem is. I tried mtdblock0 too but it does not work.
Which drivers are needed? Or can you provide an older version?

**Comment by zonesan** [comment]
Hi, I think you may need to update the burntool.

**Comment by Haragius** [comment]
Thx it seems to work. Sorry about this post.
