### ISSUE TITLE
Cannot connect to my ap

### ISSUE THREAD

**Issue by asadman1523** [Lamobo/Lamobo-D1#4]
I link to 192.168.0.1 and wanna set the wireless to my ap

But I set the password and click save button. It doesn't connected to my AP.

Is the webpage wrong?

**Comment by zonesan** [comment]
Hi, did you press function key button on D1 after saving your WiFi password?

Regards,
San

**Comment by asadman1523** [comment]
I press function key after saving WiFi password. Then the light keep bright but I cannot see any connection from my ap.

**Comment by asadman1523** [comment]
It works! I press the wrong key sorry! :)
